/:
  controller: main
  action: home

/login:
  controller: user
  action: login

/logout:
  controller: user
  action: logout
    
/register:
  controller: user
  action: register

/confirmaccount:
  controller: user
  action: confirmaccount

/dashboard:
  controller: admin
  action: home

/mail:
  controller: mail
  action: main


/forgetPassword:
  controller: user
  action: forgetPswd
/sendPasswordReset:
  controller: user
  action: sendPswdRst
/changePassword:
  controller: user
  action: changePswd
/confirmChange:
  controller: user
  action: confirmChng

/redi:
  controller: user
  action: redi


  # ajout 
# routes CRUD articles
/createArticle:
  controller: article
  action: articleCreate
  

/detailsArticle:
  controller: article
  action: detailsArticle
  

/updateArticle:
  controller: article
  action: updateArticle


/deleteArticle:
  controller: article
  action: deleteArticle
  

/articles:
  controller: article
  action: allArticle


###### comments/like ########
/comment:
  controller: comment
  action: commentCreate

/replyComment:
  controller: comment
  action: replyComment

/createLike:
  controller: like
  action: createLike

/getLikes:
  controller: like
  action: getLikes
###### comments/like ########
  
 
