/:
  controller: main
  action: home

/login:
  controller: user
  action: login

/logout:
  controller: user
  action: logout
    
/register:
  controller: user
  action: register

/confirmaccount:
  controller: user
  action: confirmaccount

/dashboard:
  controller: admin
  action: home

/mail:
  controller: mail
  action: main

#modification de mot de passe
/forgetPassword:
  controller: user
  action: forgetPswd

/changePassword:
  controller: user
  action: changePswd