/:
    controller: main
    action: home

/login:
    controller: user
    action: login

/logout:
    controller: user
    action: logout
    
/register:
  controller: user
  action: register

/dashboard:
  controller: admin
  action: home

/mail:
  controller: mail
  action: main


/forgetPassword:
  controller: user
  action: forgetPswd
/sendPasswordReset:
  controller: user
  action: sendPswdRst
/changePassword:
  controller: user
  action: changePswd
/confirmChange:
  controller: user
  action: confirmChng

/redi:
  controller: user
  action: redi