#roles mis en place

/:
  controller: main
  action: home
  role: [public]

/login:
  controller: user
  action: login
  role: [public]

/logout:
  controller: user
  action: logout
  role: [user, admin, super_admin]
    
/register:
  controller: user
  action: register
  role: [public]

/confirmaccount:
  controller: user
  action: confirmaccount
  role: [public]

/dashboard:
  controller: admin
  action: home
  role: [admin, super_admin]

/mail:
  controller: mail
  action: main
  role: [user, admin, super_admin]


/forgetPassword:
  controller: user
  action: forgetPswd
  role: [public]

/sendPasswordReset:
  controller: user
  action: sendPswdRst
  role: [public]

/changePassword:
  controller: user
  action: changePswd
  role: [user, admin, super_admin]

/confirmChange:
  controller: user
  action: confirmChng
  role: [user, admin, super_admin]

/redi:
  controller: user
  action: redi
  role: [user, admin, super_admin]


# ajout 
# routes CRUD articles
/createArticle:
  controller: article
  action: articleCreate
  role: [admin, super_admin]

/detailsArticle:
  controller: article
  action: detailsArticle
  role: [public, user, admin, super_admin]

/updateArticle:
  controller: article
  action: updateArticle
  role: [admin, super_admin]

/deleteArticle:
  controller: article
  action: deleteArticle
  role: [admin, super_admin]

/articles:
  controller: article
<<<<<<< HEAD
  action: allArticle
  role: [public, user, admin, super_admin]
 
=======
  action: indexArticle

>>>>>>> feature/slug

###### comments/like ########
/comment:
  controller: comment
  action: commentCreate
  role: [public, user, admin, super_admin]

/replyComment:
  controller: comment
  action: replyComment
  role: [public, user, admin, super_admin]

/createLike:
  controller: like
  action: createLike
  role: [public, user, admin, super_admin]

/getLikes:
  controller: like
  action: getLikes
  role: [public, user, admin, super_admin]
###### comments/like ########


###### gestion des pages ########
/addPage:
  controller: admin
  action: addPage
  
/deletePage:
  controller: admin
  action: deletePageAdmin





/la coucou page:
  controller: article
  action: indexArticle
  role: [public]
