/admin-inscription:
  controller: user
  action: register
  role: [public]

/confirmation-inscription:
  controller: user
  action: confirmaccount
  role: [public]

/login:
  controller: user
  action: login
  role: [public]

/logout:
  controller: user
  action: logout
  role: [public]

# /register:
#   controller: user
#   action: register
#   role: [public]

# inscription user
/inscription:
  controller: user
  action: register

/mail:
  controller: mail
  action: main
  role: [public]

/forgetPassword:
  controller: user
  action: forgetPswd
  role: [public]

/sendPasswordReset:
  controller: user
  action: sendPswdRst
  role: [public]

/changePassword:
  controller: user
  action: changePswd
  role: [public]

/confirmChange:
  controller: user
  action: confirmChng
  role: [public]

/redi:
  controller: user
  action: redi
  role: [public]

### SECURITY ###

### HOME ###
/:
  controller: main
  action: home
  role: [public]

/home:
  controller: main
  action: home
  role: [public]

### HOME ###

/about:
  controller: about
  action: indexAbout
  role: [public]

/contact:
  controller: contact
  action: indexContact
  role: [public]

/presentation:
  controller: presentation
  action: index
  role: [public]

###### comments/like ########
/comment:
  controller: comment
  action: commentCreate
  role: [public]

/replyComment:
  controller: comment
  action: replyComment
  role: [public]

/createLike:
  controller: like
  action: createLike
  role: [public]

/getLikes:
  controller: like
  action: getLikes
  role: [public]
###### comments/like ########

###### articles ########
/article:
  controller: article
  action: showArticle
  role: [public]

/articles:
  controller: article
  action: indexArticle
  role: [public]

###### articles ########

###### report ########

/reportComment:
  controller: comment
  action: reportComment
  role: [public]

###### report ########

###### errors ########

/page-non-trouvee:
  controller: error
  action: notFoundError
  role: [public]

/non-autorise:
  controller: error
  action: unauthorizedError
  role: [public]

/probleme-technique:
  controller: error
  action: serverError
  role: [public]

###### errors ########

##########################################
##############  FRONT   ##################
##########################################

##########################################
##############  ADMIN   ##################
##########################################

/dashboard:
  controller: admin
  action: dashboard
  role: [public]

/getStatConnexion:
  controller: admin
  action: getStatConnexion
  role: [public]

/user-profile:
  controller: user
  action: getUserProfile
  role: [public]

/user-profilePwd:
  controller: user
  action: changePwd
  role: [public]

/gerer-mes-messages:
  controller: admin
  action: indexContact
  role: [public]

/deleteContact:
  controller: admin
  action: deleteContact
  role: [public]

/devFixtures:
  controller: admin
  action: loadFixtures
  role: [public]

###### articles ########
# C #
/ecrire-un-article:
  controller: article
  action: articleCreate
  role: [public]

# U #
/editer-un-article:
  controller: article
  action: updateArticle
  role: [public]

/gerer-mes-articles:
  controller: admin
  action: indexArticle
  role: [public]

/deleteArticle:
  controller: article
  action: deleteArticle
  role: [public]

###### articles ########

###### report ########

/reports:
  controller: comment
  action: getReports
  role: [public]

###### report ########

###### categories ########
/gerer-mes-categories:
  controller: categories
  action: indexCategories
  role: [public]

/crer-une-categorie:
  controller: categories
  action: addCategory
  role: [public]

/deleteCategory:
  controller: categories
  acion: deleteCategory
  role: [public]

###### categories ########

###### pages ########

/gerer-mes-pages:
  controller: admin
  action: addPage
  role: [public]

/editPage:
  controller: admin
  action: editPage
  role: [public]

/deletePage:
  controller: admin
  action: deletePageAdmin
  role: [public]

###### pages ########

###### Menu ########
/gerer-mon-menu:
  controller: admin
  action: editMenu
  role: [public]

/moveItemPosition:
  controller: admin
  action: moveItemPosition
  role: [public]

/addItem:
  controller: admin
  action: addItem
  role: [public]







/actus:
  controller: categories
  action: categoryPage
  role: [public]

/ligue-1:
  controller: categories
  action: categoryPage
  role: [public]

/ligue-2:
  controller: categories
  action: categoryPage
  role: [public]

/foot-feminin:
  controller: categories
  action: categoryPage
  role: [public]

/champions-league:
  controller: categories
  action: categoryPage
  role: [public]

/psg:
  controller: categories
  action: categoryPage
  role: [public]

/adminmember:
 controller: admin
 action: memberview
 role: [public]

/deleteUser:
  controller: admin
  action: deleteUser
  role: [public]

/editUserRole:
  controller: admin
  action: editUserRole
  role: [public]




/tets:
  controller: presentation
  action: indexPresentation
  role: [ admin]


/kkl:
  controller: presentation
  action: indexPresentation
  role: [ admin]

/installation:
  controller: installation
  action: completeRegistration
  role: [admin]

/loading:
  controller: installation
  action: loading
  role: [admin]



