-- MySQL Script generated by MySQL Workbench
-- Tue Apr 19 19:34:31 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`role` (
  `id_role` INT NOT NULL,
  `libelle` VARCHAR(40) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id_role`));


-- -----------------------------------------------------
-- Table `mydb`.`categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categorie` (
  `id_category` INT NOT NULL,
  `libelle` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_category`));


-- -----------------------------------------------------
-- Table `mydb`.`commentaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`commentaire` (
  `id_commentaire` INT NOT NULL,
  `libelle` VARCHAR(40) NOT NULL,
  `text` VARCHAR(255) NULL,
  PRIMARY KEY (`id_commentaire`));


-- -----------------------------------------------------
-- Table `mydb`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`article` (
  `id_article` INT NOT NULL,
  `libelle` VARCHAR(50) NOT NULL,
  `text` VARCHAR(255) NULL,
  `id_categorie` INT NULL,
  `id_commentaire` INT NULL,
  PRIMARY KEY (`id_article`),
  INDEX `id_categorie_idx` (`id_categorie` ASC) VISIBLE,
  INDEX `id_commentaire_idx` (`id_commentaire` ASC) VISIBLE,
  CONSTRAINT `id_categorie`
    FOREIGN KEY (`id_categorie`)
    REFERENCES `mydb`.`categorie` (`id_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_commentaire`
    FOREIGN KEY (`id_commentaire`)
    REFERENCES `mydb`.`commentaire` (`id_commentaire`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`template`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`template` (
  `id_template` INT NOT NULL,
  `libelle` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_template`));


-- -----------------------------------------------------
-- Table `mydb`.`theme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`theme` (
  `id_theme` INT NOT NULL,
  `libelle` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_theme`));


-- -----------------------------------------------------
-- Table `mydb`.`page`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`page` (
  `id_page` INT NOT NULL,
  `libelle` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_page`));


-- -----------------------------------------------------
-- Table `mydb`.`planning`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`planning` (
  `id_planning` INT NOT NULL,
  `libelle` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_planning`));


-- -----------------------------------------------------
-- Table `mydb`.`site`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`site` (
  `id_site` INT NOT NULL,
  `libelle` VARCHAR(255) NOT NULL,
  `id_article` INT NULL,
  `id_template` INT NULL,
  `id_theme` INT NULL,
  `id_page` INT NULL,
  `id_planning` INT NULL,
  PRIMARY KEY (`id_site`),
  INDEX `id_article_idx` (`id_article` ASC) VISIBLE,
  INDEX `id_template_idx` (`id_template` ASC) VISIBLE,
  INDEX `id_theme_idx` (`id_theme` ASC) VISIBLE,
  INDEX `id_page_idx` (`id_page` ASC) VISIBLE,
  INDEX `id_planning_idx` (`id_planning` ASC) VISIBLE,
  CONSTRAINT `id_article`
    FOREIGN KEY (`id_article`)
    REFERENCES `mydb`.`article` (`id_article`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_template`
    FOREIGN KEY (`id_template`)
    REFERENCES `mydb`.`template` (`id_template`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_theme`
    FOREIGN KEY (`id_theme`)
    REFERENCES `mydb`.`theme` (`id_theme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_page`
    FOREIGN KEY (`id_page`)
    REFERENCES `mydb`.`page` (`id_page`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_planning`
    FOREIGN KEY (`id_planning`)
    REFERENCES `mydb`.`planning` (`id_planning`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `id_user` INT NOT NULL,
  `usercol` VARCHAR(45) NULL,
  `token` INT NULL,
  `firstName` VARCHAR(45) NULL,
  `last Name` VARCHAR(100) NULL,
  `statuts` VARCHAR(45) NULL,
  `creation` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `id_site` INT NULL,
  `id_role` INT NULL,
  PRIMARY KEY (`id_user`),
  INDEX `id_role_idx` (`id_role` ASC) VISIBLE,
  INDEX `id_site_idx` (`id_site` ASC) VISIBLE,
  CONSTRAINT `id_role`
    FOREIGN KEY (`id_role`)
    REFERENCES `mydb`.`role` (`id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_site`
    FOREIGN KEY (`id_site`)
    REFERENCES `mydb`.`site` (`id_site`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
